---
# defaults path of your generated credentials (e.g. database, talk, onlyoffice)
# the directory must be writeable for the user running this playbook
credential_store: ~/.nextcloud

# example of rclone config to backup to a s3 bucket

#rclone_remote: |
#      [backup-selfhosted]
#      type = s3
#      provider = AWS
#      env_auth = false
#      access_key_id = AKIxxxxx
#      secret_access_key = QMpoxxxx
#      region = us-east-1
#      acl = private
#      server_side_encryption = AES256
#      storage_class = STANDARD_IA

# redis config
redis_conf_file_name:
  CentOS: 'redis'
  Fedora: 'redis'
  Amazon: 'redis'
  Ubuntu: 'redis'
  Debian: 'redis'
  openSUSE Tumbleweed: 'nextcloud'
  openSUSE Leap: 'nextcloud'

# if inventory_name is localhost unix socket will be used
# Also use a dictionary for redis_socket to be able to configure different path for different systems?
redis_socket:
  path:    "/var/run/redis/{{ redis_conf_file_name[ansible_distribution] }}.sock"
  perm:    "770"
redis_tcp:
  address: "{{ hostvars[groups['redis'][0]].ansible_default_ipv4.address }}"
  port:    "6379"

# Some common variables used in more then roles
 
web_user:
  apache:
    RedHat: "apache"
    Debian: "www-data"
    Suse: "wwwrun" # Not tested
  nginx:
    RedHat: "nginx"
    Debian: "nginx"
    Suse: "nginx"

web_group:
  apache:
    RedHat: "apache"
    Debian: "www-data"
    Suse: "www" # Not tested
  nginx:
    RedHat: "nginx"
    Debian: "nginx"
    Suse: "nginx"

systemd_service_path:
  CentOS: '/usr/lib/systemd/system'
  Fedora: '/usr/lib/systemd/system'
  Amazon: '/usr/lib/systemd/system'
  Ubuntu: '/lib/systemd/system'
  Debian: '/lib/systemd/system'
php_socket:
  'CentOS': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Amazon': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Fedora': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Ubuntu': '/run/php/php{{ php_version }}-fpm.sock'
  'Debian': '/run/php/php{{ php_version }}-fpm.sock'
  'openSUSE Tumbleweed': "/run/php-fpm/php{{ php_version.split('.')[0] }}-fpm.sock" 
  'openSUSE Leap': "/run/php-fpm/php{{ php_version.split('.')[0] }}-fpm.sock"

# define tls-certificate for nextcloud webserver and onlyoffice

nextcloud_certificate_directory: "/etc/ssl/private"
nextcloud_certificate_common_name: "{{ nextcloud_fqdn }}"
nextcloud_certificate_key_length: ec-256
nextcloud_certificate_file: "{{ nextcloud_certificate_directory }}/{{ nextcloud_certificate_common_name }}/{{ nextcloud_certificate_common_name }}.crt"
nextcloud_certificate_key: "{{ nextcloud_certificate_directory }}/{{ nextcloud_certificate_common_name }}/{{ nextcloud_certificate_common_name }}.key"
nextcloud_certificate_fullchain: "{{ nextcloud_certificate_directory }}/{{ nextcloud_certificate_common_name }}/fullchain.crt"
nextcloud_certificate_csr: "{{ nextcloud_certificate_directory }}/{{ nextcloud_certificate_common_name }}/{{ nextcloud_certificate_common_name }}.csr"
nextcloud_certificate_ca: "{{ nextcloud_certificate_directory }}/{{ nextcloud_certificate_common_name }}/ca.crt"
nextcloud_certificate_test: false
