---
# defaults path of your generated credentials (e.g. database, talk, onlyoffice)
# the directory must be writeable for the user running this playbook
credential_store: ~/.nextcloud

# example of rclone config to backup to a s3 bucket

#rclone_remote: |
#      [backup-selfhosted]
#      type = s3
#      provider = AWS
#      env_auth = false
#      access_key_id = AKIxxxxx
#      secret_access_key = QMpoxxxx
#      region = us-east-1
#      acl = private
#      server_side_encryption = AES256
#      storage_class = STANDARD_IA

# redis config
# if inventory_name is localhost unix socket will be useed
redis_socket:
  path:    "/var/run/redis/redis.sock"
  perm:    "770"
redis_tcp:
  address: "{{ hostvars[groups['redis'][0]].ansible_default_ipv4.address }}"
  port:    "6379"

# Some common variables used in more then roles
 
web_user:
  CentOS: "nginx"
  Fedora: "nginx"
  Amazon: "nginx"
  Ubuntu: "www-data"
  Debian: "www-data"

web_group:
  CentOS: "nginx"
  Fedora: "nginx"
  Amazon: "nginx"
  Ubuntu: "www-data"
  Debian: "www-data"

systemd_service_path:
  CentOS: '/usr/lib/systemd/system'
  Fedora: '/usr/lib/systemd/system'
  Amazon: '/usr/lib/systemd/system'
  Ubuntu: '/lib/systemd/system'
  Debian: '/lib/systemd/system'

# temporary defined here
# needed by webserver and onlyoffice
certificates_path: '/etc/ssl/nextcloud'