---
# Some common variables used in more then roles

php_version: '7.3'
 
web_user:
  'CentOS': 'nginx'
  'Amazon': 'nginx'
  'Ubuntu': 'www-data'
  'Debian': 'www-data'

web_group:
  'CentOS': 'nginx'
  'Amazon': 'nginx'
  'Ubuntu': 'www-data'
  'Debian': 'www-data'

pg_user_id:
  'CentOS': '70'
  'Amazon': '70'
  'Ubuntu': '70'
  'Debian': '70'

pg_group_id:
  'CentOS': '70'
  'Amazon': '70'
  'Ubuntu': '70'
  'Debian': '70'

credential_store: /etc/nextcloud
dhparam_path:     /etc/nextcloud/dhparam/dhparam.pem