---
# vars file for prep_nginx

php_socket:
  'CentOS': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Amazon': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Fedora': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Ubuntu': '/run/php/php{{ php_version }}-fpm.sock'
  'Debian': '/run/php/php{{ php_version }}-fpm.sock'
