---
# tasks file for prep_postgres

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: create {{ nc_db }} db
  postgresql_db:
    name:           "{{ nc_db }}"
    state:          present
    encoding:       UTF-8
    template:       template1
  become:           yes
  become_user:      postgres


- name: "Create {{ nc_db_user }} account"
  postgresql_user:
    encrypted:      yes
    db:             "{{ nc_db }}"
    name:           "{{ nc_db_user }}"
    password:       "{{ nc_db_passwd }}"
  become:           yes
  become_user:      postgres

- name: "Grant all privileges on database {{ nc_db }} to {{ nc_db_user }}"
  postgresql_privs:
    db:             "postgres"
    privs:          ALL
    type:           database
    obj:            "{{ nc_db }}"
    role:           "{{ nc_db_user }}"
  become: yes
  become_user:      postgres

