---
# tasks file for prep_postgres

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: install psycopg2
  pip: 
    name: psycopg2
    state: latest
  become: true

- name: ensure postgres is running
  systemd:
    name:    postgresql
    enabled: true
    state:   started

- name: create {{ nc_db }} db
  postgresql_db:
    name:           "{{ nc_db }}"
    state:          present
    encoding:       UTF-8
    template:       template1
    login_host:     '{{ nc_db_host | default(omit) }}'
    login_user:     "{{ postgres_user | default(omit) }}"
    login_password: "{{ postgres_admin_password | default(omit) }}"
  become:           yes
  become_user:      postgres


- name: "Create {{ nc_db_user }} account"
  postgresql_user:
    encrypted:      yes
    db:             "{{ nc_db }}"
    name:           "{{ nc_db_user }}"
    password:       "{{ nc_db_passwd }}"
    login_host:     '{{ nc_db_host | default(omit) }}'
    login_user:     "{{ postgres_user | default(omit) }}"
    login_password: "{{ postgres_admin_password | default(omit) }}"
  become:           yes
  become_user:      postgres

- name: "Grant all privileges on database {{ nc_db }} to {{ nc_db_user }}"
  postgresql_privs:
    db:             "postgres"
    privs:          ALL
    type:           database
    obj:            "{{ nc_db }}"
    role:           "{{ nc_db_user }}"
    login_host:     '{{ nc_db_host | default(omit) }}'
    login_user:     "{{ postgres_user | default(omit) }}"
    login_password: "{{ postgres_admin_password | default(omit) }}"
  become: yes
  become_user:      postgres
    