---
# handlers file for webserver

- name: restart webserver
  systemd:
    name: "{{ webserver_service_name[nextcloud_webserver_type][ansible_os_family] }}"
    state: restarted
  listen: "restart web services"