#!/usr/bin/env ansible-playbook

- name: Prepare the OS
  hosts: all
  become: true
  gather_facts: true

  roles:
    - os

- name: Pre-flight configuration checks
  hosts: localhost
  gather_facts: false

  roles:
    - precheck

- name: Install redis or valkey
  hosts: redis
  become: true
  gather_facts: false

  roles:
    - redis

- name: Install webserver
  hosts: webserver
  become: true
  gather_facts: false

  roles:
    - webserver

- name: Install tls certificates
  hosts: nextcloud, coturn, signal, onlyoffice
  become: true
  gather_facts: false

  roles:
    - tls-certificate

- name: Install database server
  hosts: database
  become: true
  gather_facts: false

  roles:
    - role: mariadb
      when: (nextcloud_db.type == 'mysql')
    - role: postgres
      when: (nextcloud_db.type == 'pgsql')

- name: Install Docker
  hosts: docker
  become: true
  gather_facts: false

  roles:
    - docker

- name: Install HaPR für exAPPs
  hosts: hapr
  become: true
  gather_facts: false

  roles:
    - role: exapp_hapr
      when: nextcloud_install.hapr|bool

- name: Install elasticsearch
  hosts: elasticsearch
  become: true
  gather_facts: false

  roles:
    - role: fulltextsearch
      when: nextcloud_install.fulltextsearch|bool

- name: Install nextcloudoffice
  hosts: nextcloudoffice
  become: true
  gather_facts: false

  roles:
    - role: nextcloudoffice
      when: nextcloud_install.nextcloudoffice|bool

- name: Install OnlyOffice
  hosts: onlyoffice
  become: true
  gather_facts: false

  roles:
    - role: onlyoffice
      when: nextcloud_install.onlyoffice|bool

- name: Install coturn server
  hosts: coturn
  become: true
  gather_facts: false

  roles:
    - role: coturn
      when: nextcloud_install.talk|bool

- name: Install signal server
  hosts: signal
  become: true
  gather_facts: false

  roles:
    - role: signal
      when: nextcloud_install.hpb|bool

- name: Start Docker containers
  hosts: docker
  become: true
  gather_facts: false

  tasks:
    - name: Start Docker containers
      ansible.builtin.include_tasks: roles/docker/tasks/compose_up.yml

- name: Install nextcloud
  hosts: nextcloud
  become: true
  gather_facts: false

  roles:
    - role: restic_backup
      when: restic_repo != []
    - php
    - nextcloud
    - role: postgres_analyzer
      when: nextcloud_db.type == 'pgsql'
    - php_fpm_analyser

  post_tasks:
    - name: Check install status
      ansible.builtin.uri:
        url: https://{{ nextcloud_fqdn }}/status.php
        return_content: true
        validate_certs: "{% if (tls_certificate.type == 'selfsigned') or tls_certificate_test %}no{% else %}yes{% endif %}"
      register: nextcloud_status

    - name: We are ready
      ansible.builtin.assert:
        that: nextcloud_status.json.installed
        fail_msg:
          - "Upss. Something went wrong."
          - "Your Nextcloud at https://{{ nextcloud_fqdn }} is down."
        success_msg:
          - "Your Nextcloud {{ nextcloud_status.json.version }} at https://{{ nextcloud_fqdn }} is ready."
          - "Login with user: {{ nextcloud_admin }} and password: {{ passwords.nextcloud_admin }}"
          - "Other secrets you'll find in the {{ password_file }}."
