---

- name: install nextcloud 13
  hosts: nextcloud
  connection: local
  become: true

  roles:
    - prep_os
    - { role: restic_backup,    when: backup_folder != '' }
    - prep_redis
    - prep_nginx
    - prep_php
    - { role: prep_mariadb,     when: (nc_db_type == 'mysql') and (nc_db_host == 'localhost') }
    - { role: prep_postgres,    when: (nc_db_type == 'pgsql') and (nc_db_host == 'localhost') }
    - { role: prep_letsencrypt, when: ssl_certificate_type  == 'letsencrypt' }
    - { role: prep_selfssl,     when: ssl_certificate_type  == 'selfsigned' }
    - prep_nextcloud
    - { role: prep_collabora,    when: install_collabora == 'true' }
    - nc_fail2ban
