---

- name: install nextcloud
  hosts: nextcloud
  become: true

  roles:
    - { role: prep_ufw,         when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu" }
    - prep_os
    - prep_redis
    - prep_nginx
    - prep_php
    - { role: prep_mariadb,        when: (nc_db_type == 'mysql') and (nc_db_host == 'localhost') }
    - { role: prep_postgres,       when: (nc_db_type == 'pgsql') and (nc_db_host == '') }
    - { role: prep_letsencrypt,    when: ssl_certificate_type  == 'letsencrypt' }
    - { role: prep_selfssl,        when: ssl_certificate_type  == 'selfsigned' }
    - { role: restic_backup,       when: backup_folder != '' }
    - prep_nextcloud
    - { role: prep_talk,           when: talk_install == 'true' }
    - { role: prep_collabora,      when: install_collabora == 'true' }
    - { role: prep_onlyoffice,     when: install_onlyoffice == 'true' }
    - nc_fail2ban

  post_tasks:
    - name: We are ready
      debug:
        msg: 
          - "Your Nextcloud at https://{{ fqdn }} is ready."
          - "Login with user: {{ nc_admin }} and password: {{ nc_passwd }} "
          - "Other secrets you'll find in the directory {{ credential_store }} "
