---

- name: install nextcloud 13
  hosts: nextcloud
  connection: local
  become: true

  roles:
    - prep_os
    - { role: restic_backup, when: backup_folder != '' }
    - prep_redis
    - prep_nginx
    - prep_php
    - prep_mariadb
    - prep_letsencrypt
    - prep_nextcloud
    - nc_fail2ban

