---

- name: install nextcloud 13
  hosts: nextcloud
  connection: local
  become: true

  roles:
    - prep_os
    - prep_php
    - prep_mariadb
    - prep_redis
    - prep_nginx
    - prep_letsencrypt
    - prep_nextcloud
    - nc_fail2ban

