---
- name: install amazon php7.3
  shell: amazon-linux-extras install php{{ php_version }}
  args:
    creates: /usr/bin/php

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install needed packages
  yum:
    name:
      - php
      - php-cli
      - php-fpm
      - php-gd
      - php-{% if nc_db_type == 'mysql' %}mysqlnd{% elif nc_db_type == 'pgsql' %}pgsql{% endif %}
      - php-curl
      - php-xml
      - php-intl
      - php-mbstring
      - php-json
      - php-bz2
      - php-redis
      - php-pecl-imagick
      - php-common
      - php-gmp
      - php-intl
      - php-ldap
      - php-opcache
      - php-pear
      - php-pdo
      - php-pecl-apcu
      - php-pecl-zip
    state: latest

- name: configure php
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items:
    - { file: '{{ ansible_distribution }}/cli.php.ini',  dest: '{{ php_cli_conf_dir[ansible_distribution] }}/php-cli.ini' }
  notify: restart php-fpm

- name: correct ownership /var/lib/php
  file:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  0770
  with_items: 
    - { owner: nginx,  group: nginx, name: '/var/lib/php/session' }
    - { owner: root,   group: nginx, name: '/var/lib/php/wsdlcache' }
    - { owner: root,   group: nginx, name: '/var/lib/php/opcache' }
    - { owner: root,   group: nginx, name: '/var/lib/php/peclxml' }

- name: replace opcache.max_accelerated_files=4000
  lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^opcache.max_accelerated_files=(.*)'
    line:   'opcache.max_accelerated_files=10000'
    backup: true
  notify: restart php-fpm

- name: alias php 
  copy:
    content: |
      #!/bin/bash
      alias php="php -c /etc/php-cli.ini"
    dest: /etc/profile.d/php-cli-ini.sh  
  when: false
