---

# Debian related OS tasks

- name: add sury.org/php key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: add additional repos
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main'
    validate_certs: true
    update_cache: true
    state: present

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - "{{ php_db_extension[nc_db_type] }}"
      - php{{ php_version }}-curl
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-intl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-json
      - php{{ php_version }}-bz2
      - php{{ php_version }}-ldap
      - php-apcu
      - php-imagick
      - php-smbclient
      - php-redis
      - php-imagick
    autoremove: true
    state: latest


- name: configure php
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items:
    - { file: '{{ ansible_distribution }}/cli.php.ini',  dest: '{{ php_cli_conf_dir[ansible_distribution] }}/php.ini' }
  notify: restart php-fpm
