---

- name: selinux targets
  sefcontext:
    target: "{{ item }}"
    setype: httpd_sys_rw_content_t
    state: present
  with_items: 
    - '/tmp(/.*)?'

- name: restorecon 
  command: restorecon -Rv '{{ item }}'
  loop:
    - '/tmp'
