---

# Ubuntu related OS tasks

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 7BF576066ADA65728FC7E70A8C47BE8E75BCA694
    - 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- name: add additional repos
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main'
    validate_certs: true
    update_cache: true
    state: present

- name: install additional packages
  apt:
    name: "{{ item }}"
    autoremove: true
    state: latest
  with_items:
    - php7.2-fpm
    - php7.2-gd
    - php7.2-mysql
    - php7.2-curl
    - php7.2-xml
    - php7.2-zip
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-json
    - php7.2-bz2
    - php-apcu
    - php-imagick
    - php-smb
    - php-redis
    - php-imagick


- name: configure php
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items:
    - { file: '{{ ansible_distribution }}/cli.php.ini',  dest: '{{ php_cli_conf_dir[ansible_distribution] }}/php.ini' }
  notify: restart php-fpm
