---

# Ubuntu related OS tasks

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- name: add additional repos
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main'
    validate_certs: true
    update_cache: true
    state: present

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name: "{{ item }}"
    autoremove: true
    state: latest
  with_items:
    - php7.2-fpm
    - php7.2-gd
    - "{{ php_db_extension[nc_db_type] }}"
    - php7.2-curl
    - php7.2-xml
    - php7.2-zip
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-json
    - php7.2-bz2
    - php-apcu
    - php-imagick
    - php-smbclient
    - php-redis

- name: configure php
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items:
    - { file: '{{ ansible_distribution }}/cli.php.ini',  dest: '{{ php_cli_conf_dir[ansible_distribution] }}/php.ini' }
  notify: restart php-fpm

- name: configure php postgres module
  copy:
    dest: /etc/php/7.2/mods-available/pgsql.ini
    content: |
      # configuration for PHP PostgreSQL module
      extension=pgsql.so
      
      [PostgresSQL]
      pgsql.allow_persistent = On
      pgsql.auto_reset_persistent = Off
      pgsql.max_persistent = -1
      pgsql.max_links = -1
      pgsql.ignore_notice = 0
      pgsql.log_notice = 0
    owner: root
    group: root
    mode: 0644
  when: nc_db_type == 'pgsql'
  notify: restart php-fpm

- name: configure php mysql module
  copy:
    dest: /etc/php/7.2/mods-available/pdo_mysql.ini
    content: |
      # configuration for PHP MySQL module
      extension=pdo_mysql.so
      
      [mysql]
      mysql.allow_local_infile=On
      mysql.allow_persistent=On
      mysql.cache_size=2000
      mysql.max_persistent=-1
      mysql.max_links=-1
      mysql.default_port=
      mysql.default_socket=/var/lib/mysql/mysql.sock
      mysql.default_host=
      mysql.default_user=
      mysql.default_password=
      mysql.connect_timeout=60
      mysql.trace_mode=Off
    owner: root
    group: root
    mode: 0644
  when: nc_db_type == 'mysql'
  notify: restart php-fpm

