---

- name: Set server_name in /etc/nginx/default.conf for acme.sh certificate issuance
  ansible.builtin.replace:
    path: /etc/nginx/conf.d/default.conf
    regexp: '^\s*server_name\s+.*;'
    replace: "    server_name {{ ([inventory_hostname] + (additional_certificate_fqdns | default([]))) | join(' ') }};"
  notify: restart web services

- name: Nginx started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
