---
# handlers file for redis

- name: Restart redis-server
  ansible.builtin.systemd:
    name: "{{ redis_service_name[ansible_facts['os_family']] }}.service"
    state: restarted
  listen: "Restart web services"
