---
# handlers file for redis

- name: Restart redis-server
  ansible.builtin.systemd:
    name: "{{ redis_systemd_unit[ansible_facts['os_family']] }}"
    state: restarted
  listen: "Restart web services"
