---

# create ssl certificates

- name: ensure "{{ tls_certificate_directory }}" exists
  file:
    name: "{{ tls_certificate_directory }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: use the pre-defined DH groups ffdhe4096 recommended by the IETF in [RFC 7919 https://tools.ietf.org/html/rfc7919]
  copy:
    dest: '{{ tls_certificate_directory }}/dhparam.pem'
    owner: root
    group: root
    mode:  0644
    content: |
      -----BEGIN DH PARAMETERS-----
      MIICCAKCAgEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
      +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
      87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
      YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
      7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
      ssbzSibBsu/6iGtCOGEfz9zeNVs7ZRkDW7w09N75nAI4YbRvydbmyQd62R0mkff3
      7lmMsPrBhtkcrv4TCYUTknC0EwyTvEN5RPT9RFLi103TZPLiHnH1S/9croKrnJ32
      nuhtK8UiNjoNq8Uhl5sN6todv5pC1cRITgq80Gv6U93vPBsg7j/VnXwl5B0rZp4e
      8W5vUsMWTfT7eTDp5OWIV7asfV9C1p9tGHdjzx1VA0AEh/VbpX4xzHpxNciG77Qx
      iu1qHgEtnmgyqQdgCpGBMMRtx3j5ca0AOAkpmaMzy4t6Gh25PXFAADwqTs6p+Y0K
      zAqCkc3OyX3Pjsm1Wn+IpGtNtahR9EGC4caKAH5eZV9q//////////8CAQI=
      -----END DH PARAMETERS-----

- name: certificate exists
  stat:
    path: "{{ tls_certificate_file }}"
  register: cert_file

- name: check if certificate is expired
  openssl_certificate_info:
    path: "{{ tls_certificate_file }}"
  register: cert_info
  when: cert_file.stat.exists
  
- name: include certifictes tasks
  include_tasks: '{{ tls_certificate_type }}.yml'
  when: ( not cert_file.stat.exists ) or ( cert_info.expired )