---

- name: create cert directory
  file:
    name: "{{ tls_cert_key | dirname }}"
    owner: root
    group: root
    state: directory

- name: generate an openssl private key with the default values
  openssl_privatekey:
    path: "{{ tls_cert_key }}"

- name: generate an openssl certificate signing request
  openssl_csr:
    path: "{{ tls_cert_csr }}"
    privatekey_path: "{{ tls_cert_key }}"
    common_name: "{{ nextcloud_fqdn }}"

- name: generate a self signed openssl certificate
  openssl_certificate:
    path: "{{ tls_cert_file }}"
    privatekey_path: "{{ tls_cert_key }}"
    csr_path: "{{ tls_cert_csr }}"
    provider: selfsigned
