---

- name: create cert directory
  file:
    name: "{{ item }}"
    owner: root
    group: root
    mode:  0755
    state: directory
  loop:
    - "{{ tls_certificate_file | dirname }}"
    - "{{ tls_certificate_directory }}" 

- name: generate an openssl ca key with the default values
  openssl_privatekey:
    path: "{{ tls_certificate_directory }}/root.ca.key"

- name: generate an openssl certificate signing request
  openssl_csr:
    path: "{{ tls_certificate_directory }}/root.ca.csr"
    privatekey_path: "{{ tls_certificate_directory }}/root.ca.key"
    common_name: "{{ tls_certificate_common_name }}"

- name: generate a self signed openssl certificate
  openssl_certificate:
    path: "{{ tls_certificate_ca }}"
    privatekey_path: "{{ tls_certificate_directory }}/root.ca.key"
    csr_path: "{{ tls_certificate_directory }}/root.ca.csr"
    provider: selfsigned

# --------------

- name: generate an openssl private key with the default values
  openssl_privatekey:
    path: "{{ tls_certificate_key }}"
    owner: "{{ tls_certificate_owner | default('root') }}"
    group: "{{ tls_certificate_group | default('root') }}"

- name: generate an openssl certificate signing request
  openssl_csr:
    path: "{{ tls_certificate_csr }}"
    privatekey_path: "{{ tls_certificate_key }}"
    common_name: "{{ tls_certificate_common_name }}"

- name: generate a self signed openssl certificate
  openssl_certificate:
    path: "{{ tls_certificate_file }}"
    privatekey_path: "{{ tls_certificate_key }}"
    csr_path: "{{ tls_certificate_csr }}"
    ownca_path: "{{ tls_certificate_ca }}"
    ownca_privatekey_path: "{{ tls_certificate_directory }}/root.ca.key"
    owner: "{{ tls_certificate_owner | default('root') }}"
    group: "{{ tls_certificate_group | default('root') }}"
    provider: ownca

# https://stackoverflow.com/a/54373284
# Lookups occur on the local computer, not on the remote computer.
# Therefore, if this playbook uses different hosts than localhost, it will throw an error
# - debug: msg="{{ lookup('file', tls_certificate_ca ) }}" verbosity=2
# - debug: msg="{{ lookup('file', tls_certificate_file ) }}" verbosity=2
- name: get content of file {{ tls_certificate_ca }}
  command: "cat {{ tls_certificate_ca }}"
  register: tls_certificate_ca_content
  changed_when: False
  
- name: get content of file {{ tls_certificate_file }}
  command: "cat {{ tls_certificate_file }}"
  register: tls_certificate_file_content
  changed_when: False

- name: create fullchain certificate
  copy:
    dest: "{{ tls_certificate_fullchain }}"
    content: |
      {{ tls_certificate_ca_content.stdout }}
      
      {{ tls_certificate_file_content.stdout }}
    owner: "{{ tls_certificate_owner | default('root') }}"
    group: "{{ tls_certificate_group | default('root') }}"
    mode: '0644'
