---
# CentOS related tasks

- name: add epel repo
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    gpgkey: https://getfedora.org/static/352C64E5.txt
    gpgcheck: yes
    failovermethod: priority
    enabled: 1

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install needed packages
  yum:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - wget
      - perl-File-FcntlLock 
      - ImageMagick
      - ghostscript
      - postfix
      - firewalld
      - facter
      - policycoreutils-python
    state: latest
    enablerepo: epel 

- name: remove unneeded packages
  yum:
    name: python-requests
    state: absent

