---
# CentOS related tasks

# Disable SELinux
- selinux:
    state: permissive
  when: ansible_os_family == "RedHat"

- name: add epel repo
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    gpgkey: https://getfedora.org/static/352C64E5.txt
    gpgcheck: yes
    failovermethod: priority
    enabled: 1

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install needed packages
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: epel 
  with_items:
    - zip
    - unzip
    - bzip2
    - screen
    - python2-pip
    - curl
    - wget
    - perl-File-FcntlLock 
    - ImageMagick
    - postfix
    - firewalld
    - facter
    
- name: remove unneeded packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - python-requests
