---
# Fedora related tasks

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install needed packages
  yum:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - wget
      - cronie
      - perl-File-FcntlLock 
      - ImageMagick
      - ghostscript
      - postfix
      - firewalld
      - facter
      - policycoreutils-python
    state: latest
    enablerepo: epel 

- name: enable cronie
  systemd:
    name:    'crond.service'
    state:   'started'
    enabled: true