---
# Ubuntu related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - ffmpeg
      - imagemagick 
      - libfile-fcntllock-perl
      - language-pack-en-base
      - software-properties-common
      - facter
    state: latest
