---
# vars file for php

php_yum_repo_typ: "{{ 'fedora' if ansible_facts['distribution'] == 'Fedora' else 'enterprise' }}"

php_db_extension:
  mysql: php{{ php_version }}-mysql
  pgsql: php{{ php_version }}-pgsql

php_service_name:
  RedHat: php-fpm
  Debian: php{{ php_version }}-fpm

php_fpm_conf:
  RedHat: /etc/php-fpm.conf
  Debian: /etc/php/{{ php_version }}/fpm/php-fpm.conf

php_www_conf:
  RedHat: /etc/php-fpm.d/www.conf
  Debian: /etc/php/{{ php_version }}/fpm/pool.d/www.conf

php_confd:
  RedHat: /etc/php.d
  Debian: /etc/php/{{ php_version }}/fpm/conf.d

php_cli_confd:
  RedHat: /etc/php.d
  Debian: /etc/php/{{ php_version }}/cli/conf.d

php_package_required:
  yum:
    - php
    - php-cli
    - php-fpm
    - php-sodium
    - php-curl
    - php-common
    - php-gd
    - php{% if php_version.split('.')[0] | int < 8 %}-json{% endif %}
    - php-mbstring
    - php-xml
    - php-intl
    - php-pecl-apcu
    - php-redis
    - php-opcache
    - php-pecl-imagick
    - php-gmp
    - php-bcmath
    - php-bz2
    - php-pecl-zip
    - php-{% if nextcloud_db.type == 'mysql' %}mysqlnd{% elif nextcloud_db.type == 'pgsql' %}pgsql{% endif %}
    - php-pear
  apt:
    - php{{ php_version }}
    - php{{ php_version }}-cli
    - php{{ php_version }}-fpm
    - php{{ php_version }}-curl
    - php{{ php_version }}-common
    - php{{ php_version }}-gd
    - php{{ php_version }}{% if php_version.split('.')[0] | int < 8 %}-json{% endif %}
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-xml
    - php{{ php_version }}-intl
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-gmp
    - php{{ php_version }}-apcu
    - php{{ php_version }}-opcache
    - php{{ php_version }}-redis
    - php{{ php_version }}-imagick
    - php{{ php_version }}-bz2
    - php{{ php_version }}-zip
    - "{{ php_db_extension[nextcloud_db.type] }}"
    - php-pear

php_package_optional:
  yum:
    - php-smbclient
    - php-imap
    - php-ldap
  apt:
    - php{{ php_version }}-smbclient
    - php{{ php_version }}-ldap
    - php{{ php_version }}-imap
