---
# tasks file for prep_colabra

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: install python docker
  pip:
    name:
      - pip
      - docker
    state: latest

- name: enable docker
  systemd:
    name:          docker
    state:         started
    enabled:       true
    daemon_reload: yes

- name: add to group docker
  user:
    name: '{{ ansible_env.SUDO_USER }}'
    append: true
    groups: docker
  when: ansible_env.SUDO_USER | default('root') != 'root'
