---

# Debian related OS tasks

- name: import elasticsearch signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add additional repos for elasticsearch
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    validate_certs: true
    update_cache: true
    state: present

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install elasticsearch packages
  apt:
    name: 
      - apt-transport-https
      - "{{ elasticsearch_jdk_version[ansible_distribution]['v' + ansible_distribution_major_version] }}"
      - elasticsearch
      - tesseract-ocr
      - tesseract-ocr-all
    autoremove: true
    state: latest
  notify: restart elasticsearch
