---
# tasks file for fulltextsearch

- name: Include os specific tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Configure elasticsearch
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    # backrefs: true
    # backup: true
  loop:
    - regexp: "^#network.host: .*$"
      line: "network.host: 127.0.0.1"
    - regexp: "xpack.security.enabled: true"
      line: "xpack.security.enabled: false"
  notify: Restart elasticsearch

- name: Enable elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: started
    enabled: true
    daemon_reload: true
