---
# tasks file for collabora installation

- name: create group lool
  group:
    name: lool
    gid: "118"
    system: true
    state: present

- name: create user lool
  user:
    name: lool
    uid: 113
    group: lool
    home: /opt/lool
    shell: /usr/sbin/nologin
    system: true
    state: present

- name: create /etc/loolwsd
  file:
    path: /etc/loolwsd
    owner: root
    group: root
    mode:  0755
    state: directory

- name: create tls certificate (collabora code)
  include_role: 
    name: tls-certificate

- name: include os specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: set allow domain {{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}
  xml:
    path: /etc/loolwsd/loolwsd.xml
    xpath: /config/storage/wopi
    attribute: allow
    set_children:
      - host: "{{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}"
    backup: yes
  notify: restart loolwsd

- name: loolwsd.xml add attribute allow domain {{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}
  xml:
    path: /etc/loolwsd/loolwsd.xml
    xpath: /config/storage/wopi/host[text()="{{ item }}"]
    attribute: allow
    value: 'true'
    backup: yes
  loop:
    - "{{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}"
  notify: restart loolwsd

- name: start loolwsd
  systemd:
    name: loolwsd.service
    state: started
    enabled: true

- name: wait until collabora is started
  wait_for:
    host: localhost
    port: 9980

