---
# tasks file for collabora installation

- name: create group cool
  group:
    name: cool
    system: true
    state: present

- name: create user cool
  user:
    name: cool
    group: cool
    home: /opt/cool
    shell: /usr/sbin/nologin
    system: true
    state: present

- name: create /etc/coolwsd
  file:
    path: /etc/coolwsd
    owner: root
    group: root
    mode:  0755
    state: directory

- name: create tls certificate (collabora code)
  include_role: 
    name: tls-certificate

- name: include os specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: set allow domain {{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}
  xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/storage/wopi
    attribute: allow
    set_children:
      - host: "{{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}"
    backup: yes
  notify: restart coolwsd

- name: coolwsd.xml add attribute allow domain {{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}
  xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/storage/wopi/host[text()="{{ item }}"]
    attribute: allow
    value: 'true'
    backup: yes
  loop:
    - "{{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}"
  notify: restart coolwsd

- name: Return motd to registered var
  ansible.builtin.command: sudo coolconfig set ssl.enable false && sudo coolconfig set ssl.termination true && sudo coolconfig set storage.wopi.host ooyetu.irdidoes.tech

- name: start coolwsd
  systemd:
    name: coolwsd.service
    state: started
    enabled: true

- name: wait until collabora is started
  wait_for:
    host: localhost
    port: 9980

