---
# yum related tasks

- name: install needed centos packages 
  yum:
    name:
      - httpd
      - httpd-devel
      - mod_ssl
      - openssh
    state: latest
  vars:
    ansible_python_interpreter: python2

