---
# vars file for nginx/apache web server

tls_certificate_type: "{{ nextcloud_certificate_type }}"
tls_certificate_directory: "{{ nextcloud_certificate_directory }}"
tls_certificate_common_name: "{{ nextcloud_certificate_common_name }}"
tls_certificate_key_length: "{{ nextcloud_certificate_key_length }}"
tls_certificate_file: "{{ nextcloud_certificate_file }}"
tls_certificate_key: "{{ nextcloud_certificate_key }}"
tls_certificate_fullchain: "{{ nextcloud_certificate_fullchain }}"
tls_certificate_csr: "{{ nextcloud_certificate_csr }}"
tls_certificate_ca: "{{ nextcloud_certificate_ca }}"
tls_certificate_test: "{{ nextcloud_certificate_test }}"

nginx_apt_repo_url:
  Ubuntu: deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
  Debian: deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx

nginx_apt_key:
  Debian:
    url: https://nginx.org/keys/nginx_signing.key
  Ubuntu:
    url: https://nginx.org/keys/nginx_signing.key

nginx_yum_repo_url:
  Amazon: http://nginx.org/packages/mainline/centos/7/$basearch/
  CentOS: http://nginx.org/packages/mainline/centos/{{ ansible_distribution_major_version|int }}/$basearch/

php_socket:
  'CentOS': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Amazon': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Fedora': '/run/php-fpm/php{{ php_version }}-fpm.sock'
  'Ubuntu': '/run/php/php{{ php_version }}-fpm.sock'
  'Debian': '/run/php/php{{ php_version }}-fpm.sock'

webserver_service_name:
  nginx:
    RedHat: nginx
    Debian: nginx
  apache:
    RedHat: httpd
    Debian: apache2

apache_server_root:
  Debian: /etc/apache2
  RedHat: /etc/httpd
  
apache_conf_path: 
  Debian: /etc/apache2
  RedHat: /etc/httpd/conf.d
  
apache_default_vhost_filename: 000-default.conf

