---
# Configure AppAPI with HaProxy Reverse Proxy (HARP)

- name: Install AppAPI app
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ app:install app_api
  args:
    chdir: "{{ nextcloud_www_dir }}"
    creates: "{{ nextcloud_www_dir }}/apps/app_api"

- name: Enable AppAPI app
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ app:enable app_api
  args:
    chdir: "{{ nextcloud_www_dir }}"

- name: Register HARP Deploy Daemon
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: >
    php occ app_api:daemon:register
    default-harp-deploy-daemon
    "HaRP Proxy (Host)"
    docker-install
    http
    127.0.0.1:8780
    https://{{ nextcloud_fqdn }}
    --set-default
    --harp
    --harp_frp_address=localhost:8782
    --harp_shared_key={{ passwords.hp_shared_key }}
  args:
    chdir: "{{ nextcloud_www_dir }}"
  register: register_daemon
  changed_when: "'already registered' not in register_daemon.stderr"
  failed_when:
    - register_daemon.rc != 0
    - "'already registered' not in register_daemon.stderr"
