---

- name: Create nextcloud log directory
  ansible.builtin.file:
    name: "/var/log/nextcloud"
    state: directory
    owner: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
    group: "{{ web_group[nextcloud_webserver_type][ansible_facts['os_family']] }}"
    mode: "0750"

- name: Configure nextcloud logging
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ {{ item }}
  args:
    chdir: "{{ nextcloud_www_dir }}"
  loop:
    - "config:system:set log_type --value=file"
    - "config:system:set logfile --value=/var/log/nextcloud/nextcloud.log"
    - "config:system:set loglevel --value={{ nextcloud_logging_level | default(2) }}"
    - "config:system:set log_rotate_size --value={{ nextcloud_logging_rotate_size | default(104857600) }}"
    - "config:system:set log_rotate_keep --value={{ nextcloud_logging_rotate_keep | default(10) }}"
    - "config:app:set admin_audit logfile --value=/var/log/nextcloud/audit.log"
    - "config:system:set log.condition apps 0 --value admin_audit"
  changed_when: false
