---
# tasks file for nextcloud office configuration

- name: Install nextcloud office app
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ app:install richdocuments
  args:
    chdir: "{{ nextcloud_www_dir }}"
    creates: "{{ nextcloud_www_dir }}/apps/richdocuments"

- name: Configure nextcloud office app
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ {{ item }}
  args:
    chdir: "{{ nextcloud_www_dir }}"
  loop:
    - app:enable richdocuments
    - "config:app:set richdocuments wopi_url --value https://{{ nextcloud_fqdn }}:{{ nextcloud_ssl_port }}"
    - "config:app:set richdocuments wopi_allowlist --value 127.0.0.1/8,::1/128,{{ docker_network_nextcloud.network.IPAM.Config[0].Subnet }},fe80::/10"
    - "config:app:set richdocuments disable_certificate_verification --value=yes"
    - richdocuments:activate-config
  changed_when: false
