---
# tasks file for onlyoffice configuration

- name: Configure OnlyOffice integration in Nextcloud
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become: true
  block:
    - name: Read installed Nextcloud apps
      ansible.builtin.command: php occ app:list --output=json
      args:
        chdir: "{{ nextcloud_www_dir }}"
      register: _nc_app_list
      changed_when: false

    - name: Install onlyoffice app
      ansible.builtin.command: php occ app:install onlyoffice
      args:
        chdir: "{{ nextcloud_www_dir }}"
      when: >
        'onlyoffice' not in
        (
          ((_nc_app_list.stdout | from_json).enabled  | default({})).keys() | list
          + ((_nc_app_list.stdout | from_json).disabled | default({})).keys() | list
        )

    - name: Enable onlyoffice app
      ansible.builtin.command: php occ app:enable onlyoffice
      args:
        chdir: "{{ nextcloud_www_dir }}"
      when: >
        'onlyoffice' not in
        ((_nc_app_list.stdout | from_json).enabled | default({})).keys() | list

    - name: Set onlyoffice server url
      ansible.builtin.command: >
        php occ config:app:set onlyoffice DocumentServerUrl
        --value https://{{ onlyoffice_fqdn }}:{{ onlyoffice_ssl_port }}
      args:
        chdir: "{{ nextcloud_www_dir }}"
      changed_when: true

    - name: Set onlyoffice server secret
      ansible.builtin.command: >
        php occ config:app:set onlyoffice jwt_secret
        --value {{ passwords.onlyoffice_secret }}
      args:
        chdir: "{{ nextcloud_www_dir }}"
      changed_when: true

    - name: Disable certificate verification for self-signed / test certs
      ansible.builtin.command: >
        php occ config:system:set onlyoffice verify_peer_off
        --value=true --type=boolean
      args:
        chdir: "{{ nextcloud_www_dir }}"
      when: (tls_certificate.type == 'selfsigned') or tls_certificate_test
      changed_when: true
