---

- name: Install talk app
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ app:install spreed
  args:
    chdir: "{{ nextcloud_www_dir }}"
    creates: "{{ nextcloud_www_dir }}/apps/spreed"

- name: Configure talk app
  vars:
    coturn_talk_host: "{{ hostvars[groups['coturn'][0]]['inventory_hostname'] }}"
    talk_turn_servers_value: >-
      [{"schemes":"turn,turns","server":"{{ coturn_talk_host }}:{{ coturn_tls_port }}","secret":"{{ passwords.coturn }}","protocols":"udp,tcp"}]
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php occ {{ item }}
  args:
    chdir: "{{ nextcloud_www_dir }}"
  loop:
    - app:enable spreed
    - config:app:set spreed stun_servers --value '["{{ coturn_talk_host }}:3478"]'
    - "config:app:set spreed turn_servers --value '{{ talk_turn_servers_value }}'"
  changed_when: false

- name: Configure HPB signaling server
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: >
    php occ config:app:set spreed signaling_servers --value
    '{
      "servers": [
        {
          "server": "https://{{ hostvars[groups["signal"][0]]["inventory_hostname"] }}/standalone-signaling/",
          "verify": {{ ((tls_certificate.type != "selfsigned") and (not tls_certificate_test)) | lower }}
        }
      ],
      "secret": "{{ passwords.signal_nextcloud_secret }}"
    }'
  args:
    chdir: "{{ nextcloud_www_dir }}"
  when: nextcloud_install.hpb|bool

- name: Configure HPB recording server
  vars:
    signal_recording_host: >-
      {{
        hostvars[groups["signal"][0]]["additional_fqdns"]["additional_fqdn_recording"]
        | default((hostvars[groups["signal"][0]]["additional_certificate_fqdns"] | default([]) | first), true)
        | default('')
      }}
    recording_servers_value: >-
      {{
        '{"servers":[{"server":"https://' ~ signal_recording_host ~ '/",'
        ~ '"verify":' ~ (((tls_certificate.type != "selfsigned") and (not tls_certificate_test)) | lower)
        ~ '}],"secret":"' ~ passwords.signal_recording_secret ~ '"}'
      }}
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: >
    php occ config:app:set spreed recording_servers --value
    '{{ recording_servers_value }}'
  args:
    chdir: "{{ nextcloud_www_dir }}"
  when:
    - nextcloud_install.hpb|bool
    - signal_recording_host | length > 0
