---
# handlers file for prep_talk

- name: restart coturn
  listen: restart coturn
  systemd:
    name: coturn
    state: restarted

- name: restart turnserver
  listen: restart turnserver
  systemd:
    name: turnserver
    state: restarted
