---
# tasks file for nextcloud
- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
       - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}_{{ansible_distribution_release}}.yml"
       - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
       - "{{ ansible_distribution }}.yml"
       - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
       - "{{ ansible_os_family }}.yml"
       - "default.yml"

- name: include os specific tasks
  include_tasks: 'os/main.yml'

- name: download nextcloud archive
  get_url:
    url:  "{{ nextcloud_archive }}"
    dest: /tmp/nextcloud.tar.bz2
    checksum: "sha256:{{ nextcloud_archive }}.sha256"

- name: install nextcloud
  unarchive: 
    src: /tmp/nextcloud.tar.bz2
    dest: "{{ www_dir }}"
    remote_src: true
    owner: "{{ web_user[nextcloud_webserver_type][ansible_os_family] }}"
    group: "{{ web_group[nextcloud_webserver_type][ansible_os_family] }}"
    mode:  "o-rwx"
    creates: "{{ nextcloud_www_dir }}/occ"

# https://github.com/nextcloud/server/issues/25436
# https://github.com/nextcloud/server/pull/25474#issuecomment-773134487
- name: Modify nextcloud code
  replace:
    path: "{{ nextcloud_www_dir }}/lib/private/DB/ConnectionFactory.php"
    regexp : ^(\s*\'row_format\' => \')compressed(\',)
    replace: \1dynamic\2
  # when: nextcloud_db_type == "mysql" and mariadb_version >=10.6 and nextcloud_version <=23
  when: nextcloud_db_type == "mysql"

- name: include selinux tasks
  include_tasks: selinux.yml
  when: 
    - (ansible_os_family == "RedHat")
    - ('status' in ansible_selinux)
    - (ansible_selinux.status == "enabled")

- name: flush all handlers to restart server
  meta: flush_handlers

- name: configure nextcloud
  include_tasks: configure/nextcloud.yml

- name: add nextcloud cronjob
  cron:
    name: nextcloud cronjob
    minute: '*/5'
    user: "{{ web_user[nextcloud_webserver_type][ansible_os_family] }}"
    job: "php -f {{ nextcloud_www_dir }}/cron.php > /dev/null 2>&1"

- name: run nextcloud cronjob
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_os_family] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: php -f {{ nextcloud_www_dir }}/cron.php
  args:
    chdir: "{{ nextcloud_www_dir }}"
  when: first_setup_nextcloud is changed

- name: configure fulltextsearch
  include_tasks: configure/fulltextsearch.yml
  when: install_fulltextsearch|bool

- name: configure collabora
  include_tasks: configure/collabora.yml
  when: install_collabora|bool

- name: configure onlyoffice
  include_tasks: configure/onlyoffice.yml
  when: install_onlyoffice|bool

- name: configure talk
  include_tasks: configure/talk.yml
  when: install_talk|bool
