---
# tasks file for nextcloud

- name: Include os specific tasks
  ansible.builtin.include_tasks: 'os/main.yml'

# - name: Include docker specific tasks
#   ansible.builtin.include_tasks: 'docker/main.yml'

- name: Include database create tasks
  ansible.builtin.include_tasks: 'database/create_{{ nextcloud_db.type }}.yml'

- name: Include webserver specific tasks
  ansible.builtin.include_tasks: 'webserver/{{ nextcloud_webserver_type }}.yml'

- name: Download nextcloud archive
  ansible.builtin.get_url:
    url: "{{ nextcloud_archive }}"
    dest: /tmp/nextcloud.tar.bz2
    mode: "0644"
    checksum: "sha256:{{ nextcloud_archive }}.sha256"

- name: Install nextcloud
  ansible.builtin.unarchive:
    src: /tmp/nextcloud.tar.bz2
    dest: /var/www
    remote_src: true
    owner: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
    group: "{{ web_group[nextcloud_webserver_type][ansible_facts['os_family']] }}"
    mode: "o-rwx"
    creates: "{{ nextcloud_www_dir }}/occ"

- name: Include selinux tasks
  ansible.builtin.include_tasks: selinux.yml
  when:
    - (ansible_facts['os_family'] == "RedHat")
    - ('status' in ansible_selinux)
    - (ansible_selinux.status == "enabled")

- name: Flush all handlers to restart server
  ansible.builtin.meta: flush_handlers

- name: Configure nextcloud
  ansible.builtin.include_tasks: configure/nextcloud.yml

- name: Configure logging
  ansible.builtin.include_tasks: configure/logging.yml

- name: Add nextcloud cronjob
  ansible.builtin.cron:
    name: nextcloud cronjob
    minute: '*/5'
    user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
    job: "php -f {{ nextcloud_www_dir }}/cron.php > /dev/null 2>&1"

- name: Run nextcloud cronjob
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_facts['os_family']] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: true
  ansible.builtin.command: php -f {{ nextcloud_www_dir }}/cron.php
  args:
    chdir: "{{ nextcloud_www_dir }}"
  when: first_setup_nextcloud is changed

- name: Configure fulltextsearch
  ansible.builtin.include_tasks: configure/fulltextsearch.yml
  when: nextcloud_install.fulltextsearch|bool

- name: Configure nextcloudoffice
  ansible.builtin.include_tasks: configure/nextcloudoffice.yml
  when: nextcloud_install.nextcloudoffice|bool

- name: Configure onlyoffice
  ansible.builtin.include_tasks: configure/onlyoffice.yml
  when: nextcloud_install.onlyoffice|bool

- name: Configure talk
  ansible.builtin.include_tasks: configure/talk.yml
  when: nextcloud_install.talk|bool

- name: Configure exAPPs HaPR
  ansible.builtin.include_tasks: configure/exapp_hapr.yml
  when: nextcloud_install.hapr|bool

- name: Configure notify_push
  ansible.builtin.include_tasks: configure/notify_push.yml
  when: nextcloud_install.notify_push|bool
