---

- name: Set selinux targets
  community.general.sefcontext:
    target: "{{ item }}"
    setype: httpd_sys_rw_content_t
    state: present
  loop:
    - '{{ nextcloud_data_dir }}(/.*)?'
    - "{{ nextcloud_www_dir }}/config(/.*)?"
    - "{{ nextcloud_www_dir }}/apps(/.*)?"
    - "{{ nextcloud_www_dir }}/assets(/.*)?"
    - "{{ nextcloud_www_dir }}/.htaccess"
    - "{{ nextcloud_www_dir }}/.user.ini"
    - "{{ nextcloud_www_dir }}/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?"

- name: Enable SELinux boolean settings
  ansible.builtin.command: setsebool -P {{ item }} on
  loop:
    - httpd_can_sendmail
    - httpd_unified
    - httpd_graceful_shutdown
    - httpd_can_network_relay
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - daemons_enable_cluster_mode
    - httpd_execmem

- name: Copy SELinux policy modules to target host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - httpd-to-php-fpm.pp
    - httpd-to-redis-socket.pp
    - httpd-to-upload-tmp.pp

- name: Install SELinux policy modules
  ansible.builtin.command: semodule -i /tmp/{{ item }}
  loop:
    - httpd-to-php-fpm.pp
    - httpd-to-redis-socket.pp
    - httpd-to-upload-tmp.pp

- name: Restore SELinux context
  ansible.builtin.command: restorecon -Rv {{ item }}
  loop:
    - "{{ nextcloud_www_dir }}"
    - '{{ nextcloud_data_dir }}'
