---

- name: selinux targets
  sefcontext:
    target: "{{ item }}"
    setype: httpd_sys_rw_content_t
    state: present
  loop: 
    - '{{ nextcloud_data_dir }}(/.*)?'
    - "{{ nextcloud_www_dir }}/config(/.*)?"
    - "{{ nextcloud_www_dir }}/apps(/.*)?"
    - "{{ nextcloud_www_dir }}/assets(/.*)?"
    - "{{ nextcloud_www_dir }}/.htaccess"
    - "{{ nextcloud_www_dir }}/.user.ini"
    - "{{ nextcloud_www_dir }}/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?"

- name: enable seboolean settings
  command: setsebool -P {{ item }} on
  loop:
    - httpd_can_sendmail
    - httpd_unified
    - httpd_graceful_shutdown
    - httpd_can_network_relay
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - daemons_enable_cluster_mode
    - httpd_execmem

- name: enable seboolean settings
  command: semodule -i {{ role_path }}/files/{{ item }}
  loop:
    - httpd-to-php-fpm.pp
    - httpd-to-redis-socket.pp
    - httpd-to-upload-tmp.pp

- name: restorecon 
  command: restorecon -Rv {{ item }}
  loop:
    - "{{ nextcloud_www_dir }}"
    - '{{ nextcloud_data_dir }}'
