---

- name: selinux targets
  sefcontext:
    target: "{{ item }}"
    setype: httpd_sys_rw_content_t
    state: present
  with_items: 
    - '{{ nc_datadir }}(/.*)?'
    - '/var/www/nextcloud/config(/.*)?'
    - '/var/www/nextcloud/apps(/.*)?'
    - '/var/www/nextcloud/assets(/.*)?'
    - '/var/www/nextcloud/.htaccess'
    - '/var/www/nextcloud/.user.ini'
    - '/var/www/nextcloud/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?'
    - '/usr/local/tmp(/.*)?'
    - '/upload_tmp(/.*)?'

- name: enable seboolean settings
  command: setsebool -P {{ item }} on
  loop:
    - httpd_can_sendmail
    - httpd_unified
    - httpd_graceful_shutdown
    - httpd_can_network_relay
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - daemons_enable_cluster_mode
    - httpd_execmem

- name: enable seboolean settings
  command: semodule -i {{ role_path }}/files/{{ item }}
  loop:
    - httpd-to-php-fpm.pp
    - httpd-to-redis-socket.pp
    - httpd-to-upload-tmp.pp

- name: restorecon 
  command: restorecon -Rv {{ item }}
  loop:
    - '/var/www/nextcloud/'
    - '{{ nc_datadir }}'
    - '/upload_tmp'
    - '/usr/local/tmp'
