---
# tasks file for prep_mariadb

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: configure mariadb
  copy:
    src: my.cnf
    dest: "{{ mariadb_conf_dir[ansible_distribution] }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb
#  when: false

- name: remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: remove test db
  mysql_db:
    name: test
    state: absent

- name: create nextcloud db
  mysql_db:
    name: "{{ nc_db }}"
    collation: utf8mb4_general_ci
    encoding: utf8mb4

- name: create nextcloud user
  mysql_user:
    name:     "{{ nc_db_user }}"
    password: "{{ nc_db_passwd }}"
    priv:     "nextcloud.*:ALL"
    state: present
