---
# apt related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    autoremove: true

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - software-properties-common
      - facter
      - lsb-release 
      - ssl-cert 
      - ca-certificates 
      - apt-transport-https 
    state: latest
