---

- name: Create password directory
  ansible.builtin.file:
    name: "{{ password_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Check if password file exists
  ansible.builtin.stat:
    path: "{{ password_file }}"
  register: os_password_file_stat
  run_once: true

- name: Read existing password file
  ansible.builtin.slurp:
    src: "{{ password_file }}"
  register: existing_passwords
  when: os_password_file_stat.stat.exists
  run_once: true

- name: Parse existing passwords
  ansible.builtin.set_fact:
    passwords: "{{ (existing_passwords.content | b64decode | from_yaml) if os_password_file_stat.stat.exists else {} }}"
  run_once: true

- name: Generate new passwords
  ansible.builtin.set_fact:
    passwords: "{{ passwords | combine({
      (item.name if item is mapping else item):
      (item.password if (item is mapping and item.password | default('') | length > 0)
       else lookup('password', '/dev/null chars=ascii_letters,digits length=32')) }) }}"
  loop: "{{ password_vars }}"
  when: (item.name if item is mapping else item) not in passwords
  run_once: true

- name: Distribute passwords to all hosts
  ansible.builtin.set_fact:
    passwords: "{{ hostvars[ansible_play_hosts | first]['passwords'] }}"

- name: Save passwords to file
  ansible.builtin.copy:
    content: "{{ passwords | to_yaml }}"
    dest: "{{ password_file }}"
    owner: root
    group: root
    mode: "0600"
  when: passwords | length > 0
