---
# init firewall

- name: initialize ufw
  block:
  - name: install ufw
    apt:
      name: ufw
      state: latest

  - name: configuring ufw
    template:
      src: etc_default_ufw.j2
      dest: /etc/default/ufw
      owner: root
      group: root
      mode: 0644
    notify: reload ufw

  - name: allow ssh
    ufw:
      name: "OpenSSH"
      rule: "allow"

  - name: configuring service
    ufw:
      state: "{{ ufw_state }}"
      logging: "{{ ufw_logging }}"

  - name: start ufw
    systemd:
      name:  ufw
      state: started
      enabled: true
    when: ufw_state == 'enabled'
  when: ansible_os_family == 'Debian'
  
- name: initialize firewalld
  block:
  - name: install needed packages
    yum:
      name:
        - nginx
      state: latest
    vars:
      ansible_python_interpreter: python2
  when: ansible_os_family == 'RedHat'

