---
# yum related os tasks

- name: add amazon epel repo
  shell: amazon-linux-extras install epel
  args:
    creates: /etc/yum.repos.d/amzn2-extras.repo
  when: ansible_distribution == 'Amazon'

- name: add epel repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'
  vars:
    ansible_python_interpreter: python2

- name: install needed amazon centos os packages
  yum:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - wget
      - firewalld
    state: latest
    enablerepo: epel 
  vars:
    ansible_python_interpreter: python2

- name: install needed centos7 packages
  yum:
    name:
      - facter
      - policycoreutils-python
    state: latest
  when: ( ansible_distribution_major_version|int <= 7 ) or ( ansible_distribution == 'Amazon' )
  vars:
    ansible_python_interpreter: python2

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest
  vars:
    ansible_python_interpreter: python2

