---
# tasks file for mariadb

- name: include os specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: create conf dir
  file:
    name: "{{ mariadb_conf_dir[ansible_distribution] | dirname }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure mariadb
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_conf_dir[ansible_distribution] }}/90-nextcloud.cfg"
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb

- name: start and enable MariaDB
  systemd:
    name: mysql
    state: started
    enabled: true

- name: remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: "{{ mariadb_socket[ansible_distribution] }}"

- name: remove test db
  mysql_db:
    name: test
    state: absent
    login_unix_socket: "{{ mariadb_socket[ansible_distribution] }}"
  
- name: create nextcloud db
  mysql_db:
    name: "{{ nextcloud_db }}"
    collation: utf8mb4_general_ci
    encoding: utf8mb4
    login_unix_socket: "{{ mariadb_socket[ansible_distribution] }}"

- name: generate db passwd if nextcloud_db_passwd is empty
  set_fact: 
    nextcloud_db_passwd: "{{ lookup('password', '{{ credential_store }}/database_secret chars=ascii_letters,digits length=32') }}"
  when: nextcloud_db_passwd == ''

- name: create nextcloud user
  mysql_user:
    name:     "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_passwd }}"
    priv:     "{{ nextcloud_db }}.*:ALL"
    host:     "{{ nextcloud_db_host }}"
    state: present
    login_unix_socket: "{{ mariadb_socket[ansible_distribution] }}"
