---
# tasks file for nc_fail2ban

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: configure fail2ban
  copy:
    src: nextcloud.conf
    dest: /etc/fail2ban/filter.d/nextcloud.conf 
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: create new jail
  template:
    src: nextcloud.local.j2
    dest: /etc/fail2ban/jail.d/nextcloud.local 
    owner: root
    group: root  
    mode: 0644
  notify: restart fail2ban

- name: enable fail2ban
  systemd:
    name: fail2ban
    enabled: true

- name: include selinux tasks
  include_tasks: selinux.yml
  when: 
  - (ansible_os_family == "RedHat")
  - ('status' in ansible_selinux)
  - (ansible_selinux.status == "enabled")
