---

- name: Enable apache mods
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_fcgi
    - setenvif
    - rewrite
    - headers
    - env
    - dir
    - mime
    - authz_core
    - alias
    - ssl
  notify: restart web services

- name: Enable apache mods for collabora office
  when: (nextcloud_install.nextcloudoffice|bool) or (nextcloud_install.hapr|bool)
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy_wstunnel
    - proxy_http
  notify: restart web services

- name: Apache global ssl defaults
  ansible.builtin.template:
    src: "webserver/apache/ssl-global.conf.j2"
    dest: "{{ apache_conf_path[ansible_facts['os_family']] }}/ssl-global.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart web services

- name: Apache php-fpm config
  ansible.builtin.template:
    dest: "{{ apache_conf_path[ansible_facts['os_family']] }}/php.conf"
    src: "webserver/apache/php.conf.j2"
    mode: "0644"
  notify: restart web services

- name: Set parameter in security.conf
  ansible.builtin.lineinfile:
    dest: "{{ apache_conf_path[ansible_facts['os_family']] }}/security.conf"
    regexp: "^{{ item.key }}.*"
    line: "{{ item.key }} {{ item.value }}"
    insertafter: ".*{{ item.key }}.*"
    state: present
    backup: true
    create: true
    mode: "0644"
  loop:
    - key: ServerSignature
      value: "Off"
    - key: ServerTokens
      value: Prod
  notify: restart web services

- name: Add nextcloud vhosts configuration
  ansible.builtin.template:
    src: "webserver/apache/nextcloud.conf.j2"
    dest: "{{ apache_conf_path[ansible_facts['os_family']] }}/nextcloud.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart web services
