---

# os related tasks on nextcloud server

- name: include os specific tasks
  include_tasks: 'os/{{ ansible_pkg_mgr }}.yml'

# apply some fixes
- name: create symbolic link to /usr/bin/gs
  file:
    src:  /usr/bin/gs
    dest: /usr/local/bin/gs
    state: link

- name: change ImageMagick settings
  lineinfile:
    path:   '{{ imagemagick_xml_path[ansible_distribution] }}'
    line:   '  <policy domain="coder" rights="read|write" pattern="{{ item }}" />'
    regexp: '(.*)<policy domain="coder" rights="(.*)" pattern="{{ item }}" />(.*)'
    insertbefore: '</policymap>'
  loop:
    - PS
    - EPI
    - PDF
    - XPS
  when: imagemagick_xml_path[ansible_distribution] != ''
