---
# yum related tasks

- name: Amazon related tasks
  block:
  - name: add amazon epel repo
    shell: amazon-linux-extras install epel
    args:
      creates: /etc/yum.repos.d/amzn2-extras.repo
  - name: install needed packages amazon linux
    yum:
      name:
#        - perl-File-FcntlLock 
        - ImageMagick
        - ghostscript
      state: latest
      enablerepo: amzn2extra-epel
    vars:
      ansible_python_interpreter: python2
  when: ansible_distribution == 'Amazon'

- name: CentOS related tasks
  block:
  - name: add epel repo centos
    yum:
      name: epel-release
      state: present

  - name: install needed centos packages
    yum:
      name:
        - ghostscript
      state: latest
      enablerepo: epel 

  - name: install needed centos7 packages
    yum:
      name:
        - perl-File-FcntlLock
        - ImageMagick
      state: latest
      enablerepo: epel
    when: ansible_distribution_major_version|int <= 7

  - name: install needed centos8 packages
    yum:
      name:
        - GraphicsMagick
        - policycoreutils-python-utils
      state: latest
      enablerepo: epel 
    when: ansible_distribution_major_version|int >= 8

  when: ansible_distribution == 'CentOS'
  vars:
    ansible_python_interpreter: python2


- name: Fedora related tasks
  block:
  - name: enable cronie 
    systemd:
      name:    'crond.service'
      state:   'started'
      enabled: true
  - name: install needed fedora packages
    yum:
      name:
      - perl-File-FcntlLock 
      - ImageMagick
      - ghostscript
      state: latest
      enablerepo: epel 
    vars:
      ansible_python_interpreter: python2
  when: ansible_distribution == 'Fedora'
