---

# CentOS related tasks
#
- name: add nginx yum repos
  yum_repository:
    name: nginx
    description: NGINX YUM repo
    baseurl: http://nginx.org/packages/mainline/centos/{{ ansible_distribution_major_version|int }}/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: 0

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install needed packages
  yum:
    name:
      - nginx
      - firewalld
    state: latest
    enablerepo: nginx

- name: open firewall ports 22/{{ nc_web_port }}/{{ nc_ssl_port }}
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: false
    state: enabled
  with_items:
    - 22/tcp
    - '{{ nc_web_port }}/tcp'
    - '{{ nc_ssl_port }}/tcp'
