---

# enable fail2ban access to nextcloud.log

- name: enable seboolean settings
  command: semodule -i {{ role_path }}/files/fail2ban-server.pp

- name: restorecon 
  command: restorecon -Rv {{ nextcloud_data_dir }}/nextcloud.log
