---

# yum related tasks

- name: install fail2ban
  yum: 
    name: 
      - fail2ban
      - fail2ban-firewalld
      - fail2ban-server
      - fail2ban-systemd
    state: latest
  vars:
    ansible_python_interpreter: python2

