---
# defaults file for nginx

nextcloud_fqdn: ""

# dns resolver (nginx reverse ip lookup) set to your nameserver in /etc/resolv.conf
# see http://blog.zorinaq.com/nginx-resolver-vulns/
nginx_resolver: "{{ lookup('file', '/etc/resolv.conf')|regex_findall('nameserver (.+)') | first | default('8.8.8.8') }}"
