---
# vars file for prep_php

php_db_extension:
  mysql: php{{ php_version }}-mysql
  pgsql: php{{ php_version }}-pgsql

php_service_name:
  CentOS: php-fpm
  Fedora: php-fpm
  Amazon: php-fpm
  Ubuntu: php{{ php_version }}-fpm
  Debian: php{{ php_version }}-fpm

php_fpm_conf_dir:
  CentOS: /etc
  Fedora: /etc
  Amazon: /etc
  Ubuntu: /etc/php/{{ php_version }}/fpm
  Debian: /etc/php/{{ php_version }}/fpm

php_cli_conf_dir:
  CentOS: /etc
  Fedora: /etc
  Amazon: /etc
  Ubuntu: /etc/php/{{ php_version }}/cli
  Debian: /etc/php/{{ php_version }}/cli

php_www_conf_dir:
  CentOS: /etc/php-fpm.d
  Fedora: /etc/php-fpm.d
  Amazon: /etc/php-fpm.d
  Ubuntu: /etc/php/{{ php_version }}/fpm/pool.d
  Debian: /etc/php/{{ php_version }}/fpm/pool.d
