---
# CentOS related OS tasks

- name: install coturn
  yum: 
    name:
      - "{{ role_path }}/files/centos_rpms/turnserver-4.5.0.7-0.el7.x86_64.rpm"
      - "{{ role_path }}/files/centos_rpms/turnserver-client-libs-4.5.0.7-0.el7.x86_64.rpm"
      - "{{ role_path }}/files/centos_rpms/turnserver-utils-4.5.0.7-0.el7.x86_64.rpm"
    state: latest

- name: set coturn pid file
  lineinfile:
    path: /etc/sysconfig/turnserver 
    regexp: '^EXTRA_OPTIONS='
    line: 'EXTRA_OPTIONS="--pidfile /var/run/turnserver/turnserver.pid"'

- name: bring /etc/turnserver/turnserver.conf in place
  template:
    src:  turnserver.conf.j2
    dest: /etc/turnserver/turnserver.conf
    owner: root
    group: root
    mode:  0644
    force: true
  notify:  restart turnserver

- name: enable turnserver
  systemd:
    name: turnserver
    state: started
    enabled: true    
