---
# CentOS related OS tasks

- name: install coturn
  yum: 
    name: "{{ item }}" 
    state: latest
  with_items:
    - "{{ role_path }}/files/centos_rpms/turnserver-4.5.0.7-0.el7.x86_64.rpm"
    - "{{ role_path }}/files/centos_rpms/turnserver-client-libs-4.5.0.7-0.el7.x86_64.rpm"
    - "{{ role_path }}/files/centos_rpms/turnserver-utils-4.5.0.7-0.el7.x86_64.rpm"

- name: enable coturn
  lineinfile:
    path: /etc/default/coturn
    regexp: '(.*)TURNSERVER_ENABLED=(.*)'
    line:   'TURNSERVER_ENABLED=1'
    backup: true
  notify: restart coturn

- name: bring /etc/turnserver/turnserver.conf in place
  template:
    src:  turnserver.conf.j2
    dest: /etc/turnserver/turnserver.conf
    owner: root
    group: root
    mode:  0644
    force: true
  notify:  restart coturn

    