---
# CentOS related OS tasks

- name: install coturn
  dnf: 
    name: coturn
    state: latest

- name: bring /etc/turnserver/turnserver.conf in place
  template:
    src:  turnserver.conf.j2
    dest: /etc/coturn/turnserver.conf
    owner: root
    group: root
    mode:  0644
    force: true
  notify:  restart coturn

- name: enable turnserver
  systemd:
    name: coturn
    state: started
    enabled: true    

- name: open firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: false
    state: enabled
  with_items:
    - 5349/tcp
    - 5349/udp

