---
# Ubuntu related OS tasks

- name: install coturn
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - coturn

- name: enable coturn at boot
  lineinfile:
    path: /etc/default/coturn
    regexp: '(.*)TURNSERVER_ENABLED=(.*)'
    line:   'TURNSERVER_ENABLED=1'
    backup: true
  notify: restart coturn

- name: bring /etc/turnserver.conf in place
  template:
    src:  turnserver.conf.j2
    dest: /etc/turnserver.conf
    owner: root
    group: root
    mode:  0644
    force: true
  notify:  restart coturn

- name: enable coturn
  systemd:
    name: coturn
    state: started
    enabled: true