---
# defaults file for prep_ufw

# ufw_rules:
#   - { [port: ""] [rule: allow] [proto: any] [from_ip: any] [to_ip: any] }
ufw_rules: 
  - { port: 22, rule: allow }
  - { port: '{{ nc_web_port }}', rule: allow }
  - { port: '{{ nc_ssl_port }}', rule: allow }

#ufw_applications:
#  - { name: OpenSSH, rule: allow, from_ip: any }
# list of rules

# list of profiles located in /etc/ufw/applications.d
ufw_applications: []

# /etc/defaut/ufw settings
ufw_ipv6: "yes"
ufw_default_input_policy: DROP
ufw_default_output_policy: ACCEPT
ufw_default_forward_policy: DROP
ufw_default_application_policy: SKIP

# firewall state: enabled | disabled
ufw_state: enabled
ufw_logging: "off"

# always reset the firewall
ufw_reset: yes