---
# yum related OS tasks

- name: install python docker via pip
  pip:
    name: docker
    state: latest

- name:  install docker on CentOS/Fedora
  block:
  - name: add docker repo
    get_url: 
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo
      dest: /etc/yum.repos.d/docker.repo
      owner: root
      group: root
      mode: 0644

  - name: install docker
    yum: 
      name: 
        - docker-ce
      state: latest
  when: ansible_distribution in ['CentOS']
  vars:
    ansible_python_interpreter: python2

- name: install docker on Amazon Linux 2
  block:
  - name: install docker
    yum: 
      name: 
        - docker
      state: latest
  when: ansible_distribution in ['Amazon']
  vars:
    ansible_python_interpreter: python2

- name: enable docker
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes

- name: fix docker backend for collabora
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/dockerd --storage-driver=devicemapper'
  register: systemdchanged

# force restart of docker rightaway
- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  when: systemdchanged.changed
