---

# CentOS related tasks

- name: install needed pip packages
  pip:
    name:
      - pyOpenSSL
      - requests
      - setuptools
      - certbot-nginx 
    state: latest

- name: letsencrypt renewal cronjob
  cron:
    name:   "letsencrypt automatic renewal"
    hour:   "3,15" 
    job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew"
