---
# tasks file for prep_letsencrypt

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: ensure "{{ dhparam_path | dirname }}" exists
  file:
    name:  "{{ dhparam_path | dirname }}"
    owner: root
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    mode:  0755
    state: directory

- name: create openssl dhparam (this may take a while)
  openssl_dhparam:
    path: "{{ dhparam_path }}"
    size: "{{ dhparam_numbits | default(4096) }}"

- name: ensure nginx is stopped nginx
  systemd:
    name: nginx
    state: stopped
    enabled: true

- name: install letsencrypt certificates
  shell: "certbot certonly --standalone --installer nginx --email {{ cert_email }} --non-interactive --domain {{ fqdn }} --agree-tos {{ cert_stage|default('') }}"
  args:
    creates: /etc/letsencrypt/live/{{ fqdn }}/cert.pem

- name: 'Add cron job for certbot renewal (if configured).'
  cron:
    name: Certbot automatic renewal.
    job: "certbot --standalone --noninteractive --agree-tos --email {{ cert_email|default('info@example.com') }} -d {{ fqdn|default('example.com') }} renew --quiet --no-self-upgrade --pre-hook 'systemctl stop nginx' --post-hook 'systemctl start nginx'"
    minute: "0"
    hour: "3"
    user: "root"
    when: {{ cert_stage|default('') }} == ''
