---
# tasks file for prep_letsencrypt

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: ensure "{{ dhparam_path | dirname }}" exists
  file:
    name:  "{{ dhparam_path | dirname }}"
    owner: root
    group: '{{ ansible_env.SUDO_USER }}'
    mode:  0755
    state: directory

- name: create openssl dhparam (this may take a while)
  openssl_dhparam:
    path: "{{ dhparam_path }}"
    size: "{{ dhparam_numbits | default(4096) }}"

- name: ensure nginx is stopped nginx
  systemd:
    name: nginx
    state: stopped
    enabled: true

- name: install letsencrypt certificates
  shell: "certbot certonly --standalone --installer nginx --email {{ cert_email }} --non-interactive --domain {{ fqdn }} --agree-tos {{ cert_stage|default('') }}"
  args:
    creates: /etc/letsencrypt/live/{{ fqdn }}/cert.pem
