---

- name: bring /etc/nginx/nginx.conf in place
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    force: true
  notify: restart web services

- name: nginx nextcloud config
  template:
    src: nextcloud.conf.j2
    dest: /etc/nginx/conf.d/nextcloud.conf
    owner: root
    group: root
    mode: 0644
  notify: restart web services

- name: nginx header config
  template:
    src: header.conf.j2
    dest: /etc/nginx/conf.d/header.conf
    owner: root
    group: root
    mode: 0644
  notify: restart web services

- name: nginx config for ssl
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: restart web services

- name: copy some nginx config file
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
    force: true
  loop:
    - optimization.conf
    - php_optimization.conf
    - proxy.conf
  notify: restart web services
