---
# vars file for prep_onlyoffice

onlyoffice_volumes:
  selfsigned:
    - '/etc/nginx/certs/key.pem:/var/www/onlyoffice/Data/certs/onlyoffice.key:ro'
    - '/etc/nginx/certs/cert.pem:/var/www/onlyoffice/Data/certs/onlyoffice.crt:ro'
    - '{{ dhparam_path }}:/var/www/onlyoffice/Data/certs/dhparam.pem:ro'
  letsencrypt:
    - '/etc/letsencrypt/live/{{ fqdn }}/privkey.pem:/var/www/onlyoffice/Data/certs/onlyoffice.key:ro'
    - '/etc/letsencrypt/live/{{ fqdn }}/fullchain.pem:/var/www/onlyoffice/Data/certs/onlyoffice.crt:ro'
    - '{{ dhparam_path }}:/var/www/onlyoffice/Data/certs/dhparam.pem:ro'