---
# tasks file for prep_redis

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: configure redis
  copy:
    src: redis.conf
    dest: "{{ redis_conf_path[ansible_distribution] }}/redis.conf"
    owner: root
    group: root
    mode: 0644
    force: true
  notify: restart redis-server

- name: add user {{ web_user[ansible_distribution] }} to group redis
  user:
   name:   "{{ web_user[ansible_distribution] }}"
   groups: redis

- name: start and enable redis
  systemd:
    name:    redis
    state:   started
    enabled: true

