---
# yum related OS tasks

- name: install coturn
  yum: 
    name: "{{ item }}" 
    state: latest
  with_items:
    - "{{ role_path }}/files/centos_rpms/turnserver-4.5.0.7-0.el7.x86_64.rpm"
    - "{{ role_path }}/files/centos_rpms/turnserver-client-libs-4.5.0.7-0.el7.x86_64.rpm"
    - "{{ role_path }}/files/centos_rpms/turnserver-utils-4.5.0.7-0.el7.x86_64.rpm"

- name: bring /etc/turnserver/turnserver.conf in place
  template:
    src:  turnserver.conf.j2
    dest: /etc/turnserver/turnserver.conf
    owner: root
    group: root
    mode:  0644
    force: true
  notify:  restart coturn

    