---
# handlers file for webserver

- name: Restart webserver
  ansible.builtin.systemd:
    name: "{{ webserver_service_name[nextcloud_webserver_type][ansible_facts['os_family']] }}"
    state: restarted
  listen: "restart web services"
