---
# apt related OS tasks

- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add postgresql to sources list
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    validate_certs: true
    update_cache: true
    state: present

- name: apt install postgresql-{{ postgresql_version }} with update
  apt:
    name: "{{ postgresql_packages[ansible_distribution] }}"
    state: latest
    update_cache: true

- name: ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  loop: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: force-restart postgresql after new locales are generated.
  systemd:
    name: "{{ postgresql_daemon[ansible_distribution] }}"
    state: restarted
  when: locale_gen_result.changed
