---
# configure tasks for postgresql 

- name: configure global settings
  lineinfile:
    dest: "{{ postgresql_config_path[ansible_distribution] }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  loop: "{{ postgresql_global_config_options }}"
  notify: restart postgresql

- name: configure host based authentication (if entries are configured)
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_path[ansible_distribution] }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql
  when: postgresql_hba_entries | length > 0

- name: ensure postgresql unix socket dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 02775
  loop: "{{ postgresql_unix_socket_directories }}"