---

# create nextcloud database

- name: create {{ nextcloud_db }} db
  postgresql_db:
    name:           "{{ nextcloud_db }}"
    state:          present
    encoding:       UTF-8
    template:       template1
  become:           yes
  become_user:      postgres
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: generate db passwd if nextcloud_db_passwd is empty
  set_fact: 
    nextcloud_db_passwd: "{{ lookup('password', '{{ credential_store }}/database_secret chars=ascii_letters,digits length=32') }}"
  when: nextcloud_db_passwd == ''

- name: "Create {{ nextcloud_db_user }} account"
  postgresql_user:
    encrypted:      yes
    db:             "{{ nextcloud_db }}"
    name:           "{{ nextcloud_db_user }}"
    password:       "{{ nextcloud_db_passwd }}"
  become:           yes
  become_user:      postgres
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: "Grant all privileges on database {{ nextcloud_db }} to {{ nextcloud_db_user }}"
  postgresql_privs:
    db:             "postgres"
    privs:          ALL
    type:           database
    obj:            "{{ nextcloud_db }}"
    role:           "{{ nextcloud_db_user }}"
  become: yes
  become_user:      postgres
  vars:
    ansible_python_interpreter: /usr/bin/python3
  