---
# tasks file for postgres

- name: include os specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: initialize postgresql
  include_tasks: "initialize.yml"

- name: configure postgresql
  include_tasks: "configure.yml"

- name: create nextcloud database
  include_tasks: "database.yml"
