---

# postgres settings, used in various roles

postgres_run_dir: "/var/run/postgresql"

postgres_allowed_ipv6: "::1/128"

postgresql_user:  postgres
postgresql_group: postgres

postgresql_unix_socket_directories:
  - /var/run/postgresql

postgresql_global_config_options: []
#  - unix_socket_directories: '{{ postgresql_unix_socket_directories | join(",") }}'

postgresql_yum_repo_rpm: "{{ 'F' if ansible_facts['distribution'] == 'Fedora' else 'EL' }}-{{ ansible_facts['distribution_major_version']|int }}-x86_64/pgdg-{{ 'fedora' if ansible_facts['distribution'] == 'Fedora' else 'redhat' }}"

postgresql_packages:
  RedHat:
    - postgresql{{ postgresql_version }}-server
  Debian:
    - postgresql-{{ postgresql_version }}
  Suse:
    - postgresql{{ postgresql_version }}-server

postgresql_python_packages:
  RedHat:
    - python3-psycopg2
  Debian:
    - python3-psycopg2
  Suse:
    - python313-psycopg2

postgresql_data_dir:
  RedHat: "/var/lib/pgsql/{{ postgresql_version }}/data"
  Debian: "/var/lib/postgresql/{{ postgresql_version }}/main"
  Suse: "/var/lib/pgsql/{{ postgresql_version }}/data"

postgresql_bin_path:
  RedHat: "/usr/pgsql-{{ postgresql_version }}/bin"
  Debian: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
  Suse: "/usr/pgsql-{{ postgresql_version }}/bin"

postgresql_config_path:
  RedHat: "/var/lib/pgsql/{{ postgresql_version }}/data"
  Debian: "/etc/postgresql/{{ postgresql_version }}/main"
  Suse: "/var/lib/pgsql/{{ postgresql_version }}/data"

postgresql_daemon:
  RedHat: "postgresql-{{ postgresql_version }}"
  Debian: "postgresql@{{ postgresql_version }}-main"
  Suse: "postgresql-{{ postgresql_version }}"

postgresql_daemon_service_name: "{{ postgresql_daemon[ansible_facts['os_family']] }}"

postgresql_locales:
  - 'en_US.UTF-8'

# mariadb settings, used in various roles
mariadb_socket:
  RedHat: /var/lib/mysql/mysql.sock
  Debian: /var/run/mysqld/mysqld.sock
  Suse: /var/run/mysql/mysql.sock

mariadb_conf_dir:
  RedHat: /etc/my.cnf.d
  Debian: /etc/mysql/mariadb.conf.d/
  Suse: /etc/my.cnf.d
